a = input('Digite algo: ')
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está capitalizada?', a.istitle())
print('Está em maiúscula?', a.isupper())
print('Está em minúscula?',a.islower())
print('É só espeço?',a.isspace())
